# Generated by Django 6.0.6 on 2026-06-30 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('gms', models.CharField(blank=True, max_length=50, null=True, verbose_name='GMS Identificador')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa Contratada')),
                ('fiscal', models.CharField(max_length=255, verbose_name='Fiscal Designado')),
                ('tipo_objeto', models.CharField(choices=[('Serviços', 'Serviços'), ('Consumo', 'Consumo'), ('Permanente', 'Permanente')], default='Serviços', max_length=20, verbose_name='Tipo de Objeto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Global')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Já Pago')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término / Vigência')),
            ],
        ),
        migrations.CreateModel(
            name='ItemContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria do Item')),
                ('descricao', models.TextField(verbose_name='Descrição / Insumo')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade Contratada')),
                ('qtd_consumida', models.IntegerField(default=0, verbose_name='Quantidade Consumida/Entregue')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Unitário')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos.contrato')),
            ],
        ),
    ]
