# Generated by Django 6.0.6 on 2026-07-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcontrato',
            name='contrato',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='ItemContrato',
        ),
    ]
