# Generated by Django 6.0.6 on 2026-07-28 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0002_remove_itemcontrato_contrato_delete_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
