# Generated by Django 6.0.6 on 2026-07-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Plano/Iniciativa')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('ano_inicio', models.IntegerField(verbose_name='Ano de Início')),
                ('ano_fim', models.IntegerField(verbose_name='Ano de Conclusão')),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Plano Estratégico PDTIC',
                'verbose_name_plural': 'Planos Estratégicos PDTIC',
                'ordering': ['-criado_em'],
            },
        ),
    ]
