# Generated by Django 6.0 on 2026-04-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCAItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordem', models.IntegerField(unique=True)),
                ('tipo_item', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria_contratacao', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_objeto', models.TextField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('riscos_nao_contratacao', models.TextField(blank=True, null=True)),
                ('municipios', models.TextField(blank=True, null=True)),
                ('valor_unitario', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_total', models.CharField(blank=True, max_length=100, null=True)),
                ('grau_prioridade', models.CharField(blank=True, max_length=100, null=True)),
                ('data_pretendida', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidade_prevista', models.CharField(blank=True, max_length=255, null=True)),
                ('duracao_total', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
