# Generated by Django 6.0 on 2026-04-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pca', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PCAItem',
        ),
    ]
