# Generated by Django 6.0.6 on 2026-07-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pca', '0002_delete_pcaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCAItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordem', models.IntegerField(unique=True, verbose_name='Número de Ordem')),
                ('tipo_item', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Item')),
                ('descricao_objeto', models.TextField(blank=True, null=True, verbose_name='Descrição Sucinta do Objeto')),
                ('valor_total', models.FloatField(default=0.0, verbose_name='Estimativa de Valor Total')),
            ],
        ),
    ]
