# Generated by Django 6.0.6 on 2026-06-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Módulo')),
                ('slug', models.SlugField(help_text='Nome usado na URL, sem espaços.', unique=True)),
                ('url_destino', models.URLField(verbose_name='URL de Destino')),
                ('ativo', models.BooleanField(default=True, verbose_name='Módulo Ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Módulo do Sistema',
                'verbose_name_plural': 'Módulos do Sistema',
            },
        ),
    ]
