# Generated by Django 6.0.6 on 2026-07-28 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Instituição')),
                ('sigla', models.CharField(default='', max_length=20, verbose_name='Sigla')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(default='', max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(default='', max_length=14, verbose_name='CPF')),
                ('cargo', models.CharField(default='', max_length=100, verbose_name='Cargo')),
                ('lotacao', models.CharField(default='', max_length=150, verbose_name='Lotação / Departamento')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='E-mail Institucional')),
                ('origem', models.CharField(choices=[('SESP', 'SESP'), ('CELEPAR', 'CELEPAR'), ('EXTERNO', 'Órgão Externo / Universidade')], default='SESP', max_length=20)),
                ('tipo_acesso', models.CharField(choices=[('ANALISTA', 'Acesso direto a banco de dados (Analista)'), ('APLICACAO', 'Usuário de sistema (Conta Técnica/Aplicação)')], default='ANALISTA', max_length=20)),
                ('dados_especificos', models.JSONField(default=dict, verbose_name='Dados Técnicos')),
                ('termo_confidencialidade', models.BooleanField(default=False)),
                ('termo_lgpd', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('CRIADA', 'Solicitação Criada'), ('EM_ANALISE_DPO', 'Em Análise pelo DPO'), ('RECUSADA_DPO', 'Recusada pelo DPO'), ('EM_ANALISE_CONTROLADOR', 'Em Análise pelo Controlador'), ('CONCLUIDA', 'Solicitação Concluída (Ativo)'), ('INATIVO', 'Acesso Revogado (Inativo)')], default='CRIADA', max_length=30)),
                ('parecer_dpo', models.TextField(blank=True, null=True, verbose_name='Justificativa DPO em caso de recusa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('solicitante_sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_controle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Acesso',
                'verbose_name_plural': 'Solicitações de Acesso',
                'ordering': ['-criado_em'],
            },
        ),
    ]
