# Generated by Django 6.0.6 on 2026-07-21 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoAcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_acesso', models.CharField(choices=[('ANALISTA', 'Acesso para Analista de Dados'), ('APLICACAO', 'Usuário de Sistema/Aplicação')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE_DPO', 'Pendente de Análise DPO'), ('RECUSADO_DPO', 'Recusado pelo DPO'), ('PENDENTE_CONTROLADOR', 'Pendente no Controlador'), ('CONCLUIDO', 'Acesso Concedido/Concluído')], default='PENDENTE_DPO', max_length=30)),
                ('dados_especificos', models.JSONField(blank=True, default=dict, help_text='Guarda os campos dinâmicos do form')),
                ('termos_aceitos', models.BooleanField(default=False, help_text='Checkbox de LGPD e Confidencialidade')),
                ('justificativa_recusa', models.TextField(blank=True, help_text='Preenchido pelo DPO em caso de recusa', null=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='governanca_dados.instituicao')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
