# Generated by Django 6.0.6 on 2026-07-21 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_acesso', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaoacesso',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Solicitação de Acesso', 'verbose_name_plural': 'Solicitações de Acesso'},
        ),
        migrations.RemoveField(
            model_name='solicitacaoacesso',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='solicitacaoacesso',
            name='justificativa_recusa',
        ),
        migrations.RemoveField(
            model_name='solicitacaoacesso',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='solicitacaoacesso',
            name='termos_aceitos',
        ),
        migrations.AddField(
            model_name='solicitacaoacesso',
            name='cargo',
            field=models.CharField(default='', max_length=100, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='solicitacaoacesso',
            name='cpf',
            field=models.CharField(default='', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='solicitacaoacesso',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail Institucional'),
        ),
        migrations.AddField(
            model_name='solicitacaoacesso',
            name='lotacao',
            field=models.CharField(default='', max_length=150, verbose_name='Lotação / Departamento'),
        ),
        migrations.AddField(
            model_name='solicitacaoacesso',
            name='nome_completo',
            field=models.CharField(default='', max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='solicitacaoacesso',
            name='origem',
            field=models.CharField(choices=[('SESP', 'SESP'), ('CELEPAR', 'CELEPAR'), ('EXTERNO', 'Órgão Externo / Universidade')], default='SESP', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitacaoacesso',
            name='parecer_dpo',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa DPO em caso de recusa'),
        ),
        migrations.AddField(
            model_name='solicitacaoacesso',
            name='solicitante_sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaoacesso',
            name='termo_confidencialidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacaoacesso',
            name='termo_lgpd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome da Instituição'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='sigla',
            field=models.CharField(default='', max_length=20, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='solicitacaoacesso',
            name='dados_especificos',
            field=models.JSONField(default=dict, verbose_name='Dados Técnicos'),
        ),
        migrations.AlterField(
            model_name='solicitacaoacesso',
            name='status',
            field=models.CharField(choices=[('CRIADA', 'Solicitação Criada'), ('EM_ANALISE_DPO', 'Em Análise pelo DPO'), ('RECUSADA_DPO', 'Recusada pelo DPO'), ('EM_ANALISE_CONTROLADOR', 'Em Análise pelo Controlador'), ('CONCLUIDA', 'Solicitação Concluída (Ativo)'), ('INATIVO', 'Acesso Revogado (Inativo)')], default='CRIADA', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitacaoacesso',
            name='tipo_acesso',
            field=models.CharField(choices=[('ANALISTA', 'Acesso direto a banco de dados (Analista)'), ('APLICACAO', 'Usuário de sistema (Conta Técnica/Aplicação)')], default='ANALISTA', max_length=20),
        ),
    ]
