# Generated by Django 6.0.6 on 2026-07-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_acesso', '0001_initial'),
    ]

    operations = [
    ]