"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Carrega as variáveis do arquivo .env local
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================
# SEGURANÇA E AMBIENTE
# ==========================================
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-(0kf(w%wvc%d&z%_7a^^v2uo_3+4rv(#yiqis(9itc-1doc#i)')

DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.base.core',
    'apps.base.usuarios',
    'apps.base.acessos',
    'apps.base.organizacao',

    'apps.planejamento.necessidades',
    'apps.planejamento.pca',
    'apps.planejamento.pei',
    'apps.planejamento.petic',
    'apps.planejamento.pdtic',
    'apps.planejamento.posic',

    'apps.contratacoes.compras',
    'apps.contratacoes.licitacoes',
    'apps.contratacoes.contratos',

    'apps.governanca.plano_gestao_riscos',
    'apps.governanca.ripds',
    'apps.governanca.controle_de_acesso',
    'apps.governanca.governanca_dados',
    'apps.governanca.relatorios',

    'apps.suporte.documentos',
    'apps.suporte.carga_dados',
    'apps.suporte.notificacoes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',  # Nossa raiz limpa!
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # ADICIONE ESTA LINHA AQUI SE ELA TIVER SUMIDO NO MERGE:
                'apps.base.context_processors.menu_superior_global', 
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ==========================================
# BANCO DE DADOS OBRIGATÓRIO 
# ==========================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]