"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
import psycopg2
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-(0kf(w%wvc%d&z%_7a^^v2uo_3+4rv(#yiqis(9itc-1doc#i)'

DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.base.core',
    'apps.base.usuarios',
    'apps.base.acessos',
    'apps.base.organizacao',

    'apps.planejamento.necessidades',
    'apps.planejamento.pca',
    'apps.planejamento.pei',
    'apps.planejamento.petic',
    'apps.planejamento.pdtic',
    'apps.planejamento.posic',

    'apps.contratacoes.compras',
    'apps.contratacoes.licitacoes',
    'apps.contratacoes.contratos',

    'apps.governanca.governanca_dados',
    'apps.governanca.plano_gestao_riscos',
    'apps.governanca.ripds',
    'apps.governanca.relatorios',

    'apps.suporte.documentos',
    'apps.suporte.carga_dados',
    'apps.suporte.notificacoes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'templates' / 'base',
            BASE_DIR / 'templates' / 'base' / 'core',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ==========================================
# LÓGICA DE FALLBACK DO BANCO DE DADOS
# ==========================================
PG_HOST = os.getenv('DB_HOST')
PG_NAME = os.getenv('DB_NAME')
PG_USER = os.getenv('DB_USER')
PG_PASSWORD = os.getenv('DB_PASSWORD')
PG_PORT = os.getenv('DB_PORT', '5432')

usar_postgres = False


if PG_HOST and PG_NAME:
    try:
        print(f"Tentando conectar ao PostgreSQL em {PG_HOST}...")
        conn = psycopg2.connect(
            host=PG_HOST,
            database=PG_NAME,
            user=PG_USER,
            password=PG_PASSWORD,
            port=PG_PORT,
            connect_timeout=3
        )
        conn.close()
        usar_postgres = True
        print("✅ Sucesso! Conectado ao PostgreSQL.")
    except Exception as e:
        print(f"❌ Falha no PostgreSQL (Timeout/Rede): Usando banco local SQLite.")

if usar_postgres:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': PG_NAME,
            'USER': PG_USER,
            'PASSWORD': PG_PASSWORD,
            'HOST': PG_HOST,
            'PORT': PG_PORT,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
# ==========================================

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]